# Generated by Django 4.2 on 2026-02-02 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_questionpaper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
    ]
