# Generated by Django 4.2.27 on 2026-02-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
