# Generated by Django 4.2 on 2026-02-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_userprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_papers/images/'),
        ),
    ]
