# Generated by Django 4.2.27 on 2026-02-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_papercategory_remove_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AddField(
            model_name='papercategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='paper_category_images/'),
        ),
    ]
