# Generated by Django 4.2 on 2026-02-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vacancies/'),
        ),
    ]
