# Generated by Django 4.2 on 2026-02-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_vacancy_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('quote', models.TextField()),
                ('image', models.ImageField(upload_to='hero/')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
