# Generated by Django 4.2.27 on 2026-02-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, unique=True)),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
