# Generated by Django 4.2 on 2026-02-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_chatbotknowledge'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementPopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/')),
                ('is_active', models.BooleanField(default=False, help_text='Only one announcement should be active at a time.')),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
